<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Api_mdl extends CI_Model {

	protected	$tbl_directorat = "MASTER_DIRECTORAT",
				$tbl_division  = "MASTER_DIVISION",
				$tbl_unit      = "MASTER_UNIT",
				$tbl_vendor    = "MASTER_VENDOR",
				$tbl_coa       = "MASTER_COA",
				$tbl_pr        = "PR_HEADER",
				$tbl_pr_lines  = "PR_LINES",
				$tbl_pr_detail = "PR_DETAIL",
				$tbl_po        = "PO_HEADER",
				$tbl_po_lines  = "PO_LINES",
				$tbl_po_detail = "PO_DETAIL";

	public function get_po_by_vendor_id( $id_vendor = false){

		$where = "";
		if($id_vendor){
			$where .= " AND ID_VENDOR = ?";
		}

		$sql = "SELECT POH.PO_HEADER_ID, POL.PO_NUMBER, POL.PO_LINE_DESC, ITEM_NAME, DESCRIPTION_PO ITEM_DESCRIPTION, QUANTITY, PRICE UNIT_PRICE,
				PO_DETAIL_AMOUNT TOTAL_PRICE, ID_VENDOR, POH.STATUS, MV.NAMA_VENDOR, POH.PO_DATE, POL.PO_PERIOD_FROM, POL.PO_PERIOD_TO, POH.PO_AMOUNT, IFNULL(RSP.AMOUNT_PAID,0) INVOICE_AMOUNT,
				IFNULL(( SELECT IFNULL(ACTION_DATE, UPDATED_DATE) LAST_DATE FROM TRX_APPROVAL_PO WHERE IS_ACTIVE = 1 AND PO_HEADER_ID = POH.PO_HEADER_ID ORDER BY ID DESC LIMIT 1), IFNULL(POH.UPDATED_DATE, POH.PO_DATE)) APPROVED_DATE
				FROM $this->tbl_po_lines POL
				INNER JOIN $this->tbl_po POH ON POL.PO_HEADER_ID = POH.PO_HEADER_ID
				INNER JOIN $this->tbl_po_detail POD ON POL.PO_LINE_ID = POD.PO_LINE_ID	
				INNER JOIN $this->tbl_vendor MV ON MV.NAMA_VENDOR = POL.VENDOR_NAME
				LEFT JOIN REPORT_STATUS_PO RSP ON POL.PO_NUMBER = RSP.PO_NUMBER
				WHERE LOWER(POH.STATUS) IN ('approved','paid','partial paid')
				$where
				ORDER BY POH.PO_HEADER_ID DESC, POL.PO_NUMBER, POD.PO_DETAIL_ID";

		return $this->db->query($sql, $id_vendor)->result_array();

	}

	public function get_gr_for_assets($po_number=false){

		$whereVal = array();
		$where = "";
		if($po_number):
			$where = " AND POL.PO_NUMBER = ?";
			$whereVal[] = $po_number;
		endif;

		$sql = " SELECT DISTINCT GH.GR_HEADER_ID, GL.ASSET_TYPE ASSET_TYPE, NO_BAST, GH.TGL_BAST DPIS, GL.NO_INVOICE INVOICE_NO,
						DATE_FORMAT(GH.CREATED_DATE, '%b-%y') PERIOD, CIP CIP_FLAG,
						GL.INVOICE_DATE TANGGAL_INVOICE,
						MJC.CODE ASSET_CATEGORY_MAYOR_CODE, MAJOR_NAME ASSET_CATEGORY_MAYOR,
						MIC.CODE ASSET_CATEGORY_MINOR_CODE, MIC.MINOR_NAME ASSET_CATEGORY_MINOR,
						GL.ITEM_NAME, GL. QUANTITY, GL.ITEM_PRICE UNIT_PRICE,
						GH.PO_NUMBER NOMOR_PO, PO.PO_AMOUNT NILAI_PO_IDR,
						POL.PO_LINE_DESC PO_DESCRIPTION, MC.NATURE NOMOR_COA,
						PR_NUMBER NOMOR_PR,
						(SELECT PIC_EMAIL FROM MASTER_APPROVAL WHERE PIC_NAME = PR.SUBMITTER LIMIT 1) EMAIL_USER,
						(SELECT PIC_NAME FROM MASTER_APPROVAL WHERE PIC_NAME = PR.SUBMITTER LIMIT 1) FULL_NAME,
						MPO.CODE DEPARTEMENT_CODE, MPO.OWNERSHIP_NAME DEPT_NAME,
						UMUR_MANFAAT UMUR_MANFAAT_TAHUN,
						MR.CODE REGION_CODE, MR.REGION,
						ML.CODE LOCATION_ASSET_CODE, ML.LOCATION LOKASI_ASET,
						MO.CODE KEPEMILIKAN_CODE, MO.OWNERSHIP_NAME KEPEMILIKAN,
						POL.VENDOR_NAME VENDOR,
						MCI.CODE CONTRACT_IDENTIFICATION_CODE, MCI.NAME CONTRACT_IDENTIFICATION,
						MPO.CODE PROJECT_OWNERSHIP_CODE,
						MD.DIRECTORAT_CODE PROJECT_OWNERSHIP,
						BUDGET_TYPE, MEREK, SERIAL_NUMBER
						FROM GR_HEADER GH
						JOIN GR_LINE GL ON GH.GR_HEADER_ID = GL.GR_HEADER_ID
						JOIN PO_HEADER PO ON GH.PO_HEADER_ID = PO.PO_HEADER_ID
						JOIN PR_HEADER PR ON PO.ID_PR_HEADER_ID = PR.PR_HEADER_ID
						JOIN PO_LINES POL ON PO.PO_HEADER_ID = POL.PO_HEADER_ID
						JOIN PR_LINES PRL ON PR.PR_HEADER_ID = PRL.PR_HEADER_ID
						JOIN PR_DETAIL PRD ON PRL.PR_LINES_ID = PRD.PR_LINES_ID
						JOIN MASTER_DIRECTORAT MD ON PR.ID_DIR_CODE = MD.ID_DIR_CODE
						LEFT JOIN MASTER_COA MC ON PRD.ID_MASTER_COA = MC.ID_MASTER_COA
						LEFT JOIN MASTER_MAJOR_CATEGORY MJC ON MJC.CODE = GL.MAJOR_CATEGORY
						LEFT JOIN MASTER_MINOR_CATEGORY MIC ON MIC.CODE = GL.MINOR_CATEGORY
						LEFT JOIN MASTER_REGION MR ON MR.CODE = GL.REGION
						LEFT JOIN MASTER_LOCATION ML ON ML.CODE = GL.LOCATION
						LEFT JOIN MASTER_PROJECT_OWNERSHIP MPO ON MPO.CODE = GL.PROJECT_OWNERSHIP_UNIT_CODE
						LEFT JOIN MASTER_OWNERSHIP MO ON MO.CODE = GH.PROJECT_OWNERSHIP
						LEFT JOIN MASTER_CONTRACT_INDETIFICATION MCI ON MCI.CODE = GH.CONTRACT
						where 1=1
						AND GH.STATUS = 'approved'
						and GL.ASSET_TYPE != 'Expense'
						AND GH.IS_REVIEW = 1
						AND PULLED = 'N'
						$where";

		return $this->db->query($sql, $whereVal)->result_array();
	}

	

}

/* End of file Api_mdl.php */
/* Location: ./application/models/Api_mdl.php */